# Generated by Django 4.1.5 on 2023-03-25 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('othername', models.CharField(max_length=250)),
                ('surname', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
