# Generated by Django 4.1.5 on 2024-06-09 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=500)),
                ('plot_number', models.CharField(blank=True, max_length=250, null=True)),
                ('extend', models.DecimalField(decimal_places=4, max_digits=10)),
                ('district', models.CharField(max_length=20)),
                ('province', models.CharField(choices=[('MTN', 'Matabeleland North'), ('MTS', 'Matabeleland South'), ('MSE', 'Mashonaland East'), ('MSW', 'Mashonaland West'), ('MSC', 'Mashonaland Central'), ('MAN', 'Manicaland'), ('MSV', 'Masvingo'), ('MID', 'Midlands'), ('HRE', 'Harare'), ('BYO', 'Bulawayo')], max_length=250)),
                ('ward', models.CharField(blank=True, max_length=10, null=True)),
                ('model', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('Old', 'Old Resettlement Scheme'), ('Sma', 'Small Scale Commercial'), ('A1T', 'Three Tier'), ('Comm', 'Communal')], max_length=250, null=True)),
                ('tenure_type', models.CharField(choices=[('Off', 'Offer Letter'), ('99', '99-Year Lease'), ('A1', 'A1 Permit'), ('AP', 'A1 Temporal Permit'), ('A2', 'A2 Permit'), ('Ttl', 'Title Deed'), ('DG', 'Deed of Grant'), ('CCT', 'Certificate of Consolidated Title'), ('Non', 'None')], max_length=50)),
                ('irrigation', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=250, null=True)),
                ('water_availability', models.CharField(choices=[('D', 'Dam'), ('R', 'River'), ('B', 'Borehole'), ('W', 'Weir'), ('Wl', 'Well'), ('N', 'None')], max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('descripiton', models.TextField()),
                ('takenup', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=5, null=True)),
                ('supporting_images', models.CharField(blank=True, max_length=250, null=True)),
                ('period', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('period_type', models.CharField(blank=True, choices=[('Y', 'Year(s)'), ('M', 'Months'), ('W', 'Weeks')], max_length=5, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('negotiable', models.CharField(blank=True, max_length=250, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersapp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('othername', models.CharField(blank=True, max_length=250, null=True)),
                ('surname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('national_id', models.CharField(max_length=30, null=True, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersapp.farmer'),
        ),
    ]
