# Generated by Django 4.1.5 on 2023-06-11 13:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_name', models.CharField(max_length=500)),
                ('plot_number', models.CharField(blank=True, max_length=250, null=True)),
                ('extend', models.DecimalField(decimal_places=4, max_digits=10)),
                ('district', models.CharField(max_length=20)),
                ('province', models.CharField(choices=[('MTN', 'Matabeleland North'), ('MTS', 'Matabeleland South'), ('MSE', 'Mashonaland East'), ('MSW', 'Mashonaland West'), ('MSC', 'Mashonaland Central'), ('MAN', 'Manicaland'), ('MSV', 'Masvingo'), ('MID', 'Midlands'), ('HRE', 'Harare'), ('BYO', 'Bulawayo')], max_length=250)),
                ('ward', models.CharField(blank=True, max_length=10, null=True)),
                ('tenure_type', models.CharField(choices=[('Off', 'Offer Letter'), ('99', '99-Year Lease'), ('A1', 'A1 Permit'), ('AP', 'A1 Temporal Permit'), ('A2', 'A2 Permit'), ('Ttl', 'Title Deed'), ('DG', 'Deed of Grant'), ('CCT', 'Certificate of Consolidated Title')], max_length=50)),
                ('irrigation', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Do you have irrigation', max_length=250, null=True)),
                ('water_availability', models.CharField(choices=[('D', 'Dam'), ('R', 'River'), ('B', 'Borehole'), ('W', 'Weir'), ('Wl', 'Well'), ('N', 'None')], max_length=250)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('othername', models.CharField(blank=True, max_length=250, null=True)),
                ('surname', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('national_id', models.CharField(max_length=30, null=True, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('descripiton', models.TextField()),
                ('supporting_images', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersapp.farm')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersapp.farmer'),
        ),
    ]
