# Generated by Django 4.1.5 on 2023-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersapp', '0002_alter_farm_irrigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='takenup',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
    ]
