# Generated by Django 4.1.5 on 2023-06-03 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farmersapp', '0003_farm_venture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venture',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='venture',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='venture',
            name='supporting_images',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
