# Generated by Django 4.1.5 on 2023-06-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersapp', '0003_venture_takenup'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
