# Generated by Django 4.1.5 on 2023-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersapp', '0004_alter_venture_amount_alter_venture_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venture',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
