# Generated by Django 4.1.5 on 2023-06-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersapp', '0005_farm_model_farmer_email_venture_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='negotiable',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='venture',
            name='period',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venture',
            name='period_type',
            field=models.CharField(blank=True, choices=[('Y', 'Year(s)'), ('M', 'Months'), ('W', 'Weeks')], max_length=5, null=True),
        ),
    ]
