# Generated by Django 4.1.5 on 2023-06-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersapp', '0005_alter_venture_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='category',
        ),
        migrations.AddField(
            model_name='farm',
            name='irrigation',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='province',
            field=models.CharField(choices=[('MTN', 'Matabeleland North'), ('MTS', 'Matabeleland South'), ('MSE', 'Mashonaland East'), ('MSW', 'Mashonaland West'), ('MSC', 'Mashonaland Central'), ('MAN', 'Manicaland'), ('MSV', 'Masvingo'), ('MID', 'Midlands'), ('HRE', 'Harare'), ('BYO', 'Bulawayo')], max_length=250),
        ),
        migrations.AlterField(
            model_name='farm',
            name='tenure_type',
            field=models.CharField(choices=[('Off', 'Offer Letter'), ('99', '99-Year Lease'), ('A1', 'A1 Permit'), ('AP', 'A1 Temporal Permit'), ('A2', 'A2 Permit'), ('Ttl', 'Title Deed'), ('DG', 'Deed of Grant'), ('CCT', 'Certificate of Consolidated Title')], max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
