# Generated by Django 4.1.5 on 2023-06-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersapp', '0006_remove_farmer_category_farm_irrigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='national_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='irrigation',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Do you have irrigation', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='water_availability',
            field=models.CharField(choices=[('D', 'Dam'), ('R', 'River'), ('B', 'Borehole'), ('W', 'Weir'), ('Wl', 'Well'), ('N', 'None')], max_length=250),
        ),
    ]
